# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autocor <- function(x, lag_max) {
    .Call(`_rqapp_autocor`, x, lag_max)
}

drpd_cat <- function(t1, t2, ws) {
    .Call(`_rqapp_drpd_cat`, t1, t2, ws)
}

seq_int <- function(from, to) {
    .Call(`_rqapp_seq_int`, from, to)
}

count_if <- function(x) {
    .Call(`_rqapp_count_if`, x)
}

#' dprd_numeric
#' 
#' Cross-Recurrence diagonal profile of two continuous time-series
#' 
#' Quick method to explore the cross-recurrence diagonal profile of two
#' time series. It returns the recurrence observed for different delays, 
#' the maximal recurrence obsered and teh dealy at which it occured.
#' 
#' @param t1 a time series
#' @param t2 a time series
#' @ws a constant indicating the range of delays (positive and negative) to explore
#' @radius
#' @export
drpd_numeric <- function(t1, t2, ws, radius) {
    .Call(`_rqapp_drpd_numeric`, t1, t2, ws, radius)
}

fnn <- function(x, tao, mmax, rtol, atol) {
    .Call(`_rqapp_fnn`, x, tao, mmax, rtol, atol)
}

jrqa <- function(ts, embed = 1L, delay = 1L, normalize = 1L, rescale = 1L, mindiagline = 2L, minvertline = 2L, t_win = 1L, radius = 0.0001, whiteline = 0L, recpt = 0L) {
    .Call(`_rqapp_jrqa`, ts, embed, delay, normalize, rescale, mindiagline, minvertline, t_win, radius, whiteline, recpt)
}

mdrqa <- function(ts, embed = 1L, delay = 1L, normalize = 1L, rescale = 1L, mindiagline = 2L, minvertline = 2L, t_win = 1L, radius = 0.0001, recpt = 0L) {
    .Call(`_rqapp_mdrqa`, ts, embed, delay, normalize, rescale, mindiagline, minvertline, t_win, radius, recpt)
}

mdpsr <- function(x, dim, tau) {
    .Call(`_rqapp_mdpsr`, x, dim, tau)
}

tsHistogram <- function(x, tlag, npartitions) {
    .Call(`_rqapp_tsHistogram`, x, tlag, npartitions)
}

mutualInformation <- function(tseries, maxlag, npartitions) {
    .Call(`_rqapp_mutualInformation`, tseries, maxlag, npartitions)
}

rqa <- function(ts1, ts2, embed = 1L, delay = 1L, normalize = 1L, rescale = 1L, mindiagline = 2L, minvertline = 2L, t_win = 0L, radius = 0.0001, whiteline = 0L, recpt = 0L) {
    .Call(`_rqapp_rqa`, ts1, ts2, embed, delay, normalize, rescale, mindiagline, minvertline, t_win, radius, whiteline, recpt)
}

psr <- function(x, dim, tau) {
    .Call(`_rqapp_psr`, x, dim, tau)
}

dist_mat <- function(x1, x2, dist) {
    invisible(.Call(`_rqapp_dist_mat`, x1, x2, dist))
}

rp <- function(x, radius) {
    invisible(.Call(`_rqapp_rp`, x, radius))
}

line_stats <- function(rp, mindiagline, minvertline, t_win) {
    .Call(`_rqapp_line_stats`, rp, mindiagline, minvertline, t_win)
}

diagonal_lines <- function(rp, mindiagline) {
    .Call(`_rqapp_diagonal_lines`, rp, mindiagline)
}

vertical_lines <- function(rp, minvertline) {
    .Call(`_rqapp_vertical_lines`, rp, minvertline)
}

